services:
  - type: web
    name: whale-watcher-ai-kraken
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:$PORT main:app
    autoDeploy: true
    healthCheckPath: /signal